localizeBlankNodes expose to the cli interface.
comunica/comunica pull request #1067
Opened 2022-09-16 09:00 UTC by constraintAutomaton

using the cli interface the user can use the flag --localizeBlankNodes to force the application to use or not the blank node localization for the construct and describe query.

2022-09-16 13:02 UTC, rubensworks commented on packages/actor-query-operation-describe-subject/lib/ActorQueryOperationDescribeSubject.ts
> +    // If it was not provided by the context it will set to false and added into the context
Hmm, yes, good idea.

2022-09-16 13:08 UTC, rubensworks requested changes
Looks good! Just one minor nit.

2022-09-16 13:08 UTC, rubensworks commented on packages/actor-init-query/lib/cli/CliArgsHandlerQuery.ts
> +          describe: `Set the blank node localization.
Suggestion for a shorter one-liner: "If blank nodes should be localized per bindings entry"

2022-09-16 13:16 UTC, constraintAutomaton commented on packages/actor-query-operation-construct/lib/ActorQueryOperationConstruct.ts
> +    // Check if the we apply blank node localization
typo here

2022-09-17 05:17 UTC, merged

2022-09-17 05:17 UTC, rubensworks commented
Super, great work!