Fix DELETE/INSERT update operation order
comunica/comunica pull request #1326
Opened 2024-04-17 18:59 UTC by karelklima

Resolves #1301.

I swapped the order of operations of insert and delete streams to first delete quads and then insert. After that, updating a quad that has already been in the data source works as expected, i.e. it is not deleted.

2024-04-18 06:19 UTC, rubensworks approved these changes
Thanks @karelklima, looks like a perfect solution to me!

@jitsedesmet could you have a look at this one as well, to check if it resolves your problem as well?

2024-04-18 15:20 UTC, jitsedesmet commented
Hmm, I checked and for me, it does not solve the issue. Interestingly, though, For my use case it seems to only add the resource... :/

I am serving a minimal resource like:
```n-triples
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/Post> .
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/id> "416608218494388"^^<http://www.w3.org/2001/XMLSchema#long> .
```

A query:
```sparql
prefix ns1: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
    ?id ns1:id "416608218494388"^^xsd:long .
} INSERT {
      ?id ns1:id "416608218494389"^^xsd:long .
} where {
    ?id ns1:id "416608218494388"^^xsd:long .
}
```

I would expect the result
```n-triples
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/Post> .
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/id> "416608218494389"^^<http://www.w3.org/2001/XMLSchema#long> .
```

On master I only see the remove, resulting in:
```n-triples
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/Post> .
```

Using the solution provided by @karelklima I get:
```n-triples
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/Post> .
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/id> "416608218494388"^^<http://www.w3.org/2001/XMLSchema#long> .
<http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#416608218494388> <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/id> "416608218494389"^^<http://www.w3.org/2001/XMLSchema#long> .
```
Seems like here, only the delete works.

Full context: I am using the Community Solid Server to serve the resources, so the issue might be a compatibility issue.

2024-04-19 06:24 UTC, rubensworks commented
@jitsedesmet I also suspect we may be running into another problem there. Could you inspect the produced SPARQL queries that are sent to the CSS server? And in what order they are sent? That will probably allow us to determine whether it's the same problem or a different one.

2024-04-19 14:41 UTC, karelklima commented
I have done testing using CSS server **WITH my patch**.

I am serving resource `http://localhost/test` with content:
```sparql
<https://x/s> <https://x/p> <https://x/v1> .
<https://x/s> <https://x/p> <https://x/v2> .
```

Running the following update query:
```sparql
DELETE {
    <https://x/s> <https://x/p> <https://x/v2> .
}
INSERT {
    <https://x/s> <https://x/p> <https://x/v3> .
}
WHERE {
    <https://x/s> <https://x/p> <https://x/v2> .
}
```

Resulting in:
```sparql
<https://x/s> <https://x/p> <https://x/v1> .
<https://x/s> <https://x/p> <https://x/v3> .
```

Seems like it behaves as expected in this case, as the query correctly replaced value `v2` with `v3`.

When I run the code without the patch, the `v2` triple is just gone, which is consistent with my findings.

The script I am running: https://gist.github.com/karelklima/283f119629da41283b92c916922c0bba

One thing I noticed though - after the DELETE/INSERT query, when I query the pod file using CONSTRUCT to list all triples, Comunica does not give me updated data, but rather the original content - I assume that's because of some caching going on somewhere.

2024-04-19 15:03 UTC, karelklima commented
I also ran the test more similar to what @jitsedesmet tried:

Input:
```
<https://x/s> <https://x/p> <https://x/v1> .
```

Query:
```
DELETE {
    <https://x/s> <https://x/p> <https://x/v1> .
}
INSERT {
    <https://x/s> <https://x/p> <https://x/v2> .
}
WHERE {
    <https://x/s> <https://x/p> <https://x/v1> .
}
```

Result:
```
<https://x/s> <https://x/p> <https://x/v2> .
```

Seems fine to me. Any idea what may be the issue?

2024-04-19 15:04 UTC, rubensworks commented
Thanks for checking @karelklima!

@jitsedesmet Is it possible you are executing the query differently somehow?

> I assume that's because of some caching going on somewhere.

Indeed, that can be fixed (for now) by calling `engine.invalidateCache()`.

2024-04-20 08:58 UTC, jitsedesmet commented
I just tried again, and now it seems to work :/ (Sad smiley because I'm convinced I am doing the same thing.)
Since It's wrapped in a `Promise.all` I guess the promise handling is not always the same? I can't really explain it since I cannot recreate the problem. I am wondering whether we could just do one http request instead of awaiting two? (But that might be out of scope for this PR.)

(The only thing I changed in my system was installing `nodemon` and `node-ts` on my machine, but that could not possibly change the behaviour, right?)

2024-04-20 09:26 UTC, karelklima commented
@jitsedesmet I think you are right! I completely missed that `Promise.all` part. It seems like we are dealing with a race condition here. The execution of the promises is semi-deterministic here, depends on the destination. For `N3.Store` it behaves stable enough it seems, as there are no I/O lags and Promises evaluate right away, but in general the order of execution is non-deterministic.

Long story short - the `destination.insert` may start before `destination.delete` is finished. It works perfectly fine if the quads are distinct, but if there is an intersection then the result is basically random.

I propose the following: let's split the `Promise.all` so that we delete first, and insert new data only after the delete is finished. That is (as far as I can tell) the only way to ensure consistency.

Something like this:
```ts
const execute = (): Promise<void> => Promise.all([
    action.quadStreamDelete ? destination.delete(action.quadStreamDelete) : Promise.resolve(),
    action.deleteGraphs ?
      destination.deleteGraphs(
        action.deleteGraphs.graphs,
        action.deleteGraphs.requireExistence,
        action.deleteGraphs.dropGraphs,
      ) :
      Promise.resolve(),
  ]).then(() =>Promise.all([
    action.quadStreamInsert ? destination.insert(action.quadStreamInsert) : Promise.resolve(),
    action.createGraphs ?
      destination.createGraphs(action.createGraphs.graphs, action.createGraphs.requireNonExistence) :
      Promise.resolve(),
  ]));
```

What do you think?

2024-04-20 09:46 UTC, jitsedesmet commented
I agree with you, but I'd suggest waiting on Rubens confirmation because awaiting the deletion will also be a burden on IO delays. I suspect that we could resolve this issue in a way that requires only a single HTTP request., thus not burdening us with an increasing IO delay... :)

2024-04-20 11:18 UTC, karelklima commented
Sounds good. In order to do that, we will likely need to add a method to `IQuadDestination` interface. For example:
```typescript
interface IQuadDestination {
  update: (quadsToInsert: AsyncIterator<RDF.Quad>, quadsToDelete: AsyncIterator<RDF.Quad>) => Promise<void>;
}
```
Then we will be able to handle both fetch SPARQL and PATCH SPARQL update in one HTTP request.

2024-04-20 20:02 UTC, karelklima commented
I have implemented (hopefully) a more correct version of the DELETE/INSERT operations for various data destinations. That is by no means a final version, but rather a ground for a follow up discussion.

1) I am not sure whether the PATCH sparql update conforms to specification
2) There is a lot of duplicate code for regular SPARQL query and PATCH variant - that is by design as I expect more discrepancies in the final version
3) I am sure that the use of the async iterators can be improved

What do you think?

My original one-liner grew quite a bit :-)

2024-04-23 12:15 UTC, rubensworks requested changes
Thanks @karelklima!

While the proposed changes look great (aside from the minor comments below), they are breaking changes to the API, so we can only merge it for the next major update, which might take a while.

So I would propose the following:

1. To create a PR on the `master` branch with the removal of Promise.all, and instead run the insert/delete promises in sequence. This will be slower of course, but at least won't cause race conditions.
2. Create a separate PR on the `next/major` branch with this breaking change (including my comments). As soon as we're ready for the next major update (probably later this year when @jitsedesmet is ready with refactoring expressions), we can include this breaking change.

Does this sound ok to you @karelklima?

2024-04-23 12:15 UTC, rubensworks commented on packages/bus-rdf-update-quads/lib/IQuadDestination.ts
> +  update: (quadStreamInsert: AsyncIterator<RDF.Quad>, quadStreamDelete: AsyncIterator<RDF.Quad>) => Promise<void>;
Perhaps we can even remove the `insert` and `delete` methods, and specify `update` as having insert and delete streams each as optional.

I would also propose being able to call it as follows: `update({ insert: streamA, delete: streamB })`. (just so the order of args is not arbitrary)

2024-04-23 12:57 UTC, rubensworks commented
> Could you please elaborate how these changes are breaking to the API? If we keep the insert and delete methods on the destination interface, then we are not removing anything. Or is the addition of the update method a concern?

Indeed, the addition of `update` is the problem, as other (external) `IQuadDestination` impls would not adhere anymore.
We could also make the method optional, but that would require some unclean workarounds.

2024-04-23 19:51 UTC, karelklima commented
Closing this PR, as it is effectively replaced by #1328 and #1331.

2024-04-23 19:51 UTC, closed without merging