Send original SPARQL query string to endpoints
comunica/comunica pull request #896
Opened 2021-11-25 13:54 UTC by jasmineleonard

This is in an initial attempt to solve https://github.com/comunica/comunica/issues/844.

As suggested in the issue description, in `actor-init-sparql` we save the original query string in the context, and in `actor-query-operation-sparql-endpoint`, we check this context entry and use it if it exists.

### Questions

1. I've added `@comunica/context-entries` to the dependencies in `actor-query-operation-sparql-endpoint/package.json`, but running `yarn run lint` produces the following error:

> workspace/comunica/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts
  9:1  error  '@comunica/context-entries' should be listed in the project's dependencies. Run 'npm i -S @comunica/context-entries' to add it  import/no-extraneous-dependencies

Is there something else I need to do?  Also, do I need to update the version of `@comunica/context-entries` to reflect the addition of the new key?

2. How should I go about testing`ActorQueryOperationSparqlEndpoint.ts`?  I've added one additional test to attempt to test the new functionality added in line 89, but the test output says that both branches of this line are not covered.

3.  The issue description states that "we have to make sure that this context entry does not propagate to places where it shouldn't" and suggests "making sure that the service operator unsets or overrides this entry".  Are there any other places that we need to do this besides the service operator?

2021-11-25 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/comunica/comunica?pullRequest=896) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/comunica/comunica?pullRequest=896) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/comunica/comunica?pullRequest=896) it.</sub>

2021-11-25 15:14 UTC, rubensworks requested changes
Great work! This is very aligned with what I had in mind :-)
Just one tiny. comment

> I've added @comunica/context-entries to the dependencies in actor-query-operation-sparql-endpoint/package.json, but running yarn run lint produces the following error:

Ah, probably just an eslint caching issue (can be fixed by removing `.eslintcache`). The CI passes the lint job.

> How should I go about testingActorQueryOperationSparqlEndpoint.ts? I've added one additional test to attempt to test the new functionality added in line 89, but the test output says that both branches of this line are not covered.

I suspect the branch where the context is undefined may not be covered, so perhaps we can try adding a second test where the context is undefined (and the algebra-based query will be used).

> The issue description states that "we have to make sure that this context entry does not propagate to places where it shouldn't" and suggests "making sure that the service operator unsets or overrides this entry". Are there any other places that we need to do this besides the service operator?

AFAIK, the service operator is the only one, so your PR should have everything covered :-)

2021-11-25 15:14 UTC, rubensworks commented on packages/actor-query-operation-service/lib/ActorQueryOperationService.ts
> +    subContext = subContext.delete(KeysInitSparql.queryString);
This operation can be chained onto the previous line, so we don't need the second override of `subContext`.

2021-11-25 19:18 UTC, jasmineleonard commented
Thanks @rubensworks!

> Ah, probably just an eslint caching issue (can be fixed by removing .eslintcache)

Yes, that was it! 🤦‍♀️ 

> I suspect the branch where the context is undefined may not be covered, so perhaps we can try adding a second test where the context is undefined (and the algebra-based query will be used).

I rewrote the code slightly, as setting the context as undefined threw an error due to there not being a sparql endpoint source defined (line 77 in `ActorQueryOperationSparqlEndpoint.ts`).  This meant the code never actually reached line 89 if the context was undefined, so I've just made that explicit.  Is that an acceptable workaround?

>  AFAIK, the service operator is the only one, so your PR should have everything covered :-)

Wonderful!

2021-11-26 07:39 UTC, rubensworks approved these changes
Looks perfect!

Will merge once the CI finishes.

2021-11-26 07:45 UTC, rubensworks commented
One of the integration test fails, but this is actually expected to fail.
I will look into fixing this one myself, since our integration tests setup is a bit underdocumented atm...

2021-11-26 14:43 UTC, jasmineleonard commented
> I will look into fixing this one myself, since our integration tests setup is a bit underdocumented atm...

Thanks so much @rubensworks! 🙌

2021-11-26 14:49 UTC, merged